### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [eventsourcing/es4j#134]
Wondering if you would be willing to also make this available under ASL 2.0?

**Comment by yrashk** [comment]
Sone of the reasons for MPL are explained here https://hintjens.gitbooks.io/social-architecture/content/chapter1.html (full remixability)

Is there anything that MPL prevents you from doing?

**Comment by sirinath** [comment]
Many organisations readily have MIT, BSD, ASL 2.0, Boost whitelisted. So our preference is to rely on libraries which are more permissive.

**Comment by yrashk** [comment]
Gotcha. Actually, MPL 2.0 is quite permissive. Basically, if you change existing files, and you want to share them outside of your organization, you've got to share them under the same license. Unlike GPL, MPL covers only existing source code files but not the software package as a whole. See https://www.mozilla.org/en-US/MPL/2.0/FAQ/ Q5 and Q6 (as well as others) and if you have any extra questions about the thinking behind the licensing choice, please feel free to ping me — I am happy to explain in more details, if necessary.

Do you plan to try es4j in your organization?

**Comment by sirinath** [comment]
I am exploring the possibility. But we generally stick to BSD, MIT, ASL 2.0, Boost, ISC, zlib like licenses.

**Comment by yrashk** [comment]
@sirinath closing this issue; if you have any further questions on this matter — please don't hesitate to follow up!

Thanks for bringing this up.
