### ISSUE TITLE
Proposal: use SonarQube for code analysis 

### ISSUE THREAD

**Issue by AlexMikhalev** [eventsourcing/es4j#160]
I would like to propose to use http://docs.sonarqube.org/display/HOME/SonarQube+Platform for code analysis. 
For IntelliJ - Sonar Lint http://www.sonarlint.org/intellij/. 
It can be done as part of CI pipeline and will improve quality of the code.

**Comment by yrashk** [comment]
@AlexMikhalev thanks for the feedback. I will definitely look into this.
