### ISSUE TITLE
Bintray: eventsourcing-inmem is missing

### ISSUE THREAD

**Issue by hastebrot** [eventsourcing/es4j#71]
I can't use the dependency `"com.eventsourcing:eventsourcing-inmem:0.3.1"` because it is missing on the Bintray Maven repository [1].

Work-around: Deploy the dependency to a local maven repository.

[1] http://dl.bintray.com/eventsourcing/maven/com/eventsourcing/

**Comment by hastebrot** [comment]
Yepp, I need to deploy to local maven anyway. `LocalLockProvider` was recently introduced (or rather renamed from `MemoryLockProvider`), which is needed for the order example.

**Comment by hastebrot** [comment]
There even was no release for `eventsourcing-inmem`. I'll use the order example code under the `v0.3.2` tag [1].

Will close this issue.

[1] https://github.com/eventsourcing/es4j/tree/v0.3.2/examples/order/

**Comment by yrashk** [comment]
Yes, -inmem hasn't been released yet, it's part of 0.4.0-SNAPSHOT. Thanks for opening the issue!

**Comment by yrashk** [comment]
Another way to play with it, is to locally deploy current 0.4.0-SNAPSHOT from the HEAD, this will allow you to use current APIs before 0.4.0 is released.
